In [3]:
# Importando test_data

import pandas as pd

test_data = pd.read_csv('../bases_iniciais/test_data.csv')

test_data

,CodItem,Desc Item,Category,Family,Speciality,Testing Cost
0,70003237,"MAGNESIO, SORO (EXEMPLO DE EXPRESSAO DE RESULT...",CA,CORELAB,BIOCHEMISTRY,1.78
1,70000638,"HEMOGRAMA, AUTOMATIZADO, SANGUE",CA,HEMATO,BLOOD COUNT,2.46
2,70001597,"FERRITINA, SORO",CA,CORELAB,IMMUNOHORMONE,2.11
3,70000103,"FERRO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE ...",CA,CORELAB,BIOCHEMISTRY,0.80
4,70000224,"CALCIO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE...",CA,CORELAB,BIOCHEMISTRY,1.02
...,...,...,...,...,...,...
1997,70008635,"GENES BRCA1 E BRCA2, MLPA, SANGUE",CA,GENETICS,SPECIAL GENETICS,159.91
1998,70005303,"OBSTETRICA 1ยง TRIMESTRE (ENDOVAGINAL), SEGUNDO...",RID,ULTRASOUND,FETAL MEDICINE,111.43
1999,70006441,"HEMOFILIA A, ANALISE DO DNA, SEQUENCIAMENTO, S...",CA,GENETICS,SPECIAL GENETICS,27.03
2000,70004141,"INSULINA, SORO, 90 MIN APOS XXX",CA,CORELAB,IMMUNOHORMONE,5.55
2001,70001506,"INSULINA, SORO, 30 MIN APOS XXX",CA,CORELAB,IMMUNOHORMONE,1.99

In [4]:
# trocando nomes para padrรฃo python 

test_data = test_data.rename(columns = {'CodItem':'cod_item', 'Desc Item':'desc_item', 'Category':'category', 'Family': 'family', 'Speciality':'speciality', 'Testing Cost':'testing_cost'})
test_data

,cod_item,desc_item,category,family,speciality,testing_cost
0,70003237,"MAGNESIO, SORO (EXEMPLO DE EXPRESSAO DE RESULT...",CA,CORELAB,BIOCHEMISTRY,1.78
1,70000638,"HEMOGRAMA, AUTOMATIZADO, SANGUE",CA,HEMATO,BLOOD COUNT,2.46
2,70001597,"FERRITINA, SORO",CA,CORELAB,IMMUNOHORMONE,2.11
3,70000103,"FERRO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE ...",CA,CORELAB,BIOCHEMISTRY,0.80
4,70000224,"CALCIO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE...",CA,CORELAB,BIOCHEMISTRY,1.02
...,...,...,...,...,...,...
1997,70008635,"GENES BRCA1 E BRCA2, MLPA, SANGUE",CA,GENETICS,SPECIAL GENETICS,159.91
1998,70005303,"OBSTETRICA 1ยง TRIMESTRE (ENDOVAGINAL), SEGUNDO...",RID,ULTRASOUND,FETAL MEDICINE,111.43
1999,70006441,"HEMOFILIA A, ANALISE DO DNA, SEQUENCIAMENTO, S...",CA,GENETICS,SPECIAL GENETICS,27.03
2000,70004141,"INSULINA, SORO, 90 MIN APOS XXX",CA,CORELAB,IMMUNOHORMONE,5.55
2001,70001506,"INSULINA, SORO, 30 MIN APOS XXX",CA,CORELAB,IMMUNOHORMONE,1.99

In [5]:
# checando valores nulos

test_data.isna().sum()

cod_item        0
desc_item       0
category        0
family          0
speciality      0
testing_cost    0
dtype: int64

In [6]:
# checando valores duplicados

test_data.duplicated().sum()

0

In [7]:
# sรณ para ter certeza

test_data['cod_item'].duplicated().sum()

1

In [8]:
# checando dado com valor duplicado

test_data[test_data['cod_item'].duplicated()]

,cod_item,desc_item,category,family,speciality,testing_cost
1968,70004701,PROCEDIMENTO DIAGNOSTICO EM PAINEL DE IMUNOIST...,PA,ANATOMO,IMMUNOHISTOCHEMISTRY,362.96

In [9]:
# conferindo linhas duplicadas

test_data[test_data['cod_item'] == 70004701]

,cod_item,desc_item,category,family,speciality,testing_cost
1208,70004701,PROCEDIMENTO DIAGNOSTICO EM PAINEL DE IMUNOIST...,PA,ANATOMO,IMMUNOHISTOCHEMISTRY,362.96
1968,70004701,PROCEDIMENTO DIAGNOSTICO EM PAINEL DE IMUNOIST...,PA,ANATOMO,IMMUNOHISTOCHEMISTRY,362.96

In [10]:
# deletando repetiรงรฃo

test_data = test_data.drop(index=1968)
test_data

,cod_item,desc_item,category,family,speciality,testing_cost
0,70003237,"MAGNESIO, SORO (EXEMPLO DE EXPRESSAO DE RESULT...",CA,CORELAB,BIOCHEMISTRY,1.78
1,70000638,"HEMOGRAMA, AUTOMATIZADO, SANGUE",CA,HEMATO,BLOOD COUNT,2.46
2,70001597,"FERRITINA, SORO",CA,CORELAB,IMMUNOHORMONE,2.11
3,70000103,"FERRO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE ...",CA,CORELAB,BIOCHEMISTRY,0.80
4,70000224,"CALCIO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE...",CA,CORELAB,BIOCHEMISTRY,1.02
...,...,...,...,...,...,...
1997,70008635,"GENES BRCA1 E BRCA2, MLPA, SANGUE",CA,GENETICS,SPECIAL GENETICS,159.91
1998,70005303,"OBSTETRICA 1ยง TRIMESTRE (ENDOVAGINAL), SEGUNDO...",RID,ULTRASOUND,FETAL MEDICINE,111.43
1999,70006441,"HEMOFILIA A, ANALISE DO DNA, SEQUENCIAMENTO, S...",CA,GENETICS,SPECIAL GENETICS,27.03
2000,70004141,"INSULINA, SORO, 90 MIN APOS XXX",CA,CORELAB,IMMUNOHORMONE,5.55
2001,70001506,"INSULINA, SORO, 30 MIN APOS XXX",CA,CORELAB,IMMUNOHORMONE,1.99

In [11]:
# resetando index

test_data.reset_index(inplace=True, drop=True)
test_data

,cod_item,desc_item,category,family,speciality,testing_cost
0,70003237,"MAGNESIO, SORO (EXEMPLO DE EXPRESSAO DE RESULT...",CA,CORELAB,BIOCHEMISTRY,1.78
1,70000638,"HEMOGRAMA, AUTOMATIZADO, SANGUE",CA,HEMATO,BLOOD COUNT,2.46
2,70001597,"FERRITINA, SORO",CA,CORELAB,IMMUNOHORMONE,2.11
3,70000103,"FERRO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE ...",CA,CORELAB,BIOCHEMISTRY,0.80
4,70000224,"CALCIO, DOSAGEM, SORO (EXEMPLO DE EXPRESSAO DE...",CA,CORELAB,BIOCHEMISTRY,1.02
...,...,...,...,...,...,...
1996,70008635,"GENES BRCA1 E BRCA2, MLPA, SANGUE",CA,GENETICS,SPECIAL GENETICS,159.91
1997,70005303,"OBSTETRICA 1ยง TRIMESTRE (ENDOVAGINAL), SEGUNDO...",RID,ULTRASOUND,FETAL MEDICINE,111.43
1998,70006441,"HEMOFILIA A, ANALISE DO DNA, SEQUENCIAMENTO, S...",CA,GENETICS,SPECIAL GENETICS,27.03
1999,70004141,"INSULINA, SORO, 90 MIN APOS XXX",CA,CORELAB,IMMUNOHORMONE,5.55
2000,70001506,"INSULINA, SORO, 30 MIN APOS XXX",CA,CORELAB,IMMUNOHORMONE,1.99

In [12]:
test_data.describe(include='all')

,cod_item,desc_item,category,family,speciality,testing_cost
count,2.001000e+03,2001,2001,2001,2001,2001.000000
unique,NaN,1997,6,23,77,NaN
top,NaN,"PLAQUETAS, ANTICORPOS IGG E IGM, SORO",CA,CORELAB,IMMUNOHORMONE,NaN
freq,NaN,2,1578,990,472,NaN
mean,7.000366e+07,NaN,NaN,NaN,NaN,77.624928
std,2.266616e+03,NaN,NaN,NaN,NaN,145.963584
min,7.000004e+07,NaN,NaN,NaN,NaN,0.000000
25%,7.000166e+07,NaN,NaN,NaN,NaN,4.810000
50%,7.000358e+07,NaN,NaN,NaN,NaN,21.140000
75%,7.000534e+07,NaN,NaN,NaN,NaN,78.970000
max,7.000900e+07,NaN,NaN,NaN,NaN,1762.460000

In [13]:
# salvando e exportando base transformada

test_data.to_csv('./final_test_data.csv', sep=';', index=False)